global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'restaurant-backend'
    static_configs:
      - targets: ['restaurant-management-backend-1:5000']
